[package]
name = "phrs"
version = "0.2.0"
edition = "2024"
description = "A tabular data shell tool compatible with ph"
license = "MIT"
repository = "https://github.com/pgdr/phrs"
readme = "README.md"

[lib]
name = "phrs"
path = "src/lib.rs"

[[bin]]
name = "phrs"
path = "src/main.rs"

[dependencies]
polars = { version = "0.55.2", default-features = false, features = [
    "csv",
    "dtype-slim",
    "strings",
    "lazy",
    "diff",
    "temporal",
    "dtype-time",
]}

chrono = { version = "0.4", default-features = false, features = ["std"] }

tabulate-rs = "=0.1.0"
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
